SUBJECT_NAME = "subject"
EXP_TYPE = "human-subject"
PHASE = "exp"
TRIAL_TYPE = "non-jittering-4d"
TRIAL_NUM = 3
SAVE_DIR_IMG = f"exp-results/{SUBJECT_NAME}/{EXP_TYPE}/{PHASE}/{TRIAL_TYPE}/{TRIAL_NUM}/images"
SAVE_DIR_CSV = f"exp-results/{SUBJECT_NAME}/{EXP_TYPE}/{PHASE}/{TRIAL_TYPE}/{TRIAL_NUM}/result"
MIRROR_AXES = "x"

# paths to generate shape (randomized) - 4D (uses O/I 4th-dim moves)

# PATHS_RANDOM = [
#     "DDDBBBLLLIII"
# ]

# non jittering 4d - main pilot experiment
PATHS_RANDOM = [
    "IIILLLDDDFFF",
    "FFFIIIRRRUUU",
    "UUURRRBBBOOO",
    "UUUFFFOOOLLL",
    "OOODDDLLLBBB",
    "RRRBBBIIIDDD",
    "LLLDDDFFFOOO",
    "FFFRRRUUUOOO",
    "UUUBBBRRRIII",
    "RRRFFFOOOUUU",
    "LLLDDDIIIFFF",
    "IIIUUURRRFFF",
    "OOODDDFFFRRR",
    "IIIFFFRRRUUU",
    "BBBRRRDDDIII",
    "DDDBBBIIIRRR",
    "BBBUUURRRIII",
    "FFFDDDRRROOO",
    "UUULLLFFFOOO",
    "DDDFFFIIIRRR",
    "OOORRRBBBUUU",
    "UUUIIIFFFLLL",
    "IIIDDDBBBRRR",
    "BBBLLLUUUIII",
    "DDDFFFOOORRR",
    "OOORRRDDDBBB",
    "BBBUUUOOOLLL",
    "BBBUUULLLIII",
    "DDDRRRIIIBBB",
    "DDDRRRFFFIII",
    "RRRDDDIIIBBB",
    "LLLFFFOOOUUU",
    "UUUBBBOOORRR",
    "OOOUUUBBBRRR",
    "IIILLLBBBUUU",
    "BBBIIIDDDLLL",
    "FFFDDDLLLOOO",
    "DDDLLLBBBIII",
    "DDDBBBLLLIII",
    "LLLIIIFFFUUU",
    "BBBUUULLLOOO",
    "BBBOOOUUURRR",
    "IIIRRRBBBDDD",
    "RRRFFFIIIDDD",
    "IIIFFFLLLUUU",
    "UUULLLOOOFFF",
    "OOOBBBUUURRR",
    "BBBUUUIIILLL",
    "RRRUUUIIIBBB",
    "BBBUUUOOORRR",
]


# jittering 4d - main pilot experiment
# PATHS_RANDOM = [
#     "FFFDDDIIILLL",
#     "LLLUUUIIIBBB",
#     "FFFUUUIIILLL",
#     "RRRFFFOOODDD",
#     "DDDIIIFFFRRR",
#     "DDDRRRBBBOOO",
#     "IIILLLBBBDDD",
#     "RRRIIIBBBDDD",
#     "FFFOOORRRUUU",
#     "OOORRRUUUFFF",
#     "LLLUUUFFFOOO",
#     "RRRFFFDDDOOO",
#     "DDDLLLOOOBBB",
#     "LLLBBBUUUOOO",
#     "IIIBBBRRRDDD",
#     "UUUBBBIIILLL",
#     "BBBLLLIIIUUU",
#     "FFFLLLUUUOOO",
#     "DDDRRRFFFOOO",
#     "IIIFFFDDDLLL",
#     "OOODDDRRRFFF",
#     "OOOFFFDDDRRR",
#     "IIIRRRUUUBBB",
#     "OOOFFFLLLUUU",
#     "FFFOOOLLLUUU",
#     "DDDOOOLLLBBB",
#     "RRRIIIUUUFFF",
#     "LLLIIIFFFDDD",
#     "UUURRRIIIBBB",
#     "FFFDDDRRRIII",
#     "OOOLLLDDDBBB",
#     "BBBUUUIIIRRR",
#     "IIIRRRFFFDDD",
#     "DDDRRROOOBBB",
#     "LLLDDDBBBIII",
#     "RRRUUUFFFIII",
#     "IIIBBBDDDRRR",
#     "DDDFFFRRROOO",
#     "UUUFFFRRROOO",
#     "IIIRRRFFFUUU",
#     "BBBLLLOOODDD",
#     "FFFDDDOOOLLL",
#     "RRRFFFUUUOOO",
#     "RRROOOUUUBBB",
#     "OOODDDLLLFFF",
#     "OOODDDBBBRRR",
#     "BBBIIILLLUUU",
#     "FFFRRRDDDOOO",
#     "DDDBBBOOOLLL",
#     "LLLFFFUUUOOO",
# ]


# PATHS_RANDOM = [
#     # "UFFFLLDDDOO",
#     "UULLLDDLLOOFFF",
#     # "RRRUUURRRDD",
#     "OOORRRUUFFFRRR",
#     # "RRRDDDRRRRU",
#     "LLLUUUBBOOORRR",
#     "LLLLIIBBBUUUUO",
#     "DDDFFFLLLUUOLL",
#     "LLDDDDDLLIIBBB",
#     "OOORRRRIIIDDFF",
# ]

# PATHS_RANDOM = [
#     "DDDFFFLLIIIILL",
#     "OOUUFFRRRDDDRR",
#     "RRBBLLLLOOORRU",
#     "OOORRRRIIIILLL",
#     "IIRRDDDBBBBUUU",
#     "RRRIIIDDIIIDDD",
#     "DDDOOLLLLIIIIU",
#     "IIILLUUULLLLUU",
#     "RRUUUUIIRRRROO",
#     "OOOORRRUUFFFFI",
# ]

# PATHS_RANDOM = [
#     "UFFFLLDDDOO",
# ]

# PATHS_RANDOM = ["DRRRUUUBBBO"]

# paths to generate shape (randomized) - 3D (only R/L/U/D/F/B moves)
PATHS_RANDOM_3D = [
    "FFFRRRUUUBBB",
    "RRRBBBLLLDDD",
    "RRRBBBDDDLLL",
    "FFFDDDLLLBBB",
    "RRRBBBUUULLL",
    "UUURRRFFFDDD",
    "DDDRRRFFFRRR",
    "FFFUUUFFFRRR",
    "BBBUUUFFFLLL",
    "BBBRRRBBBDDD",
    "DDDFFFDDDRRR",
    "DDDBBBRRRBBB",
    "UUULLLUUUBBB",
    "UUUFFFDDDRRR",
    "FFFLLLBBBDDD",
    "DDDBBBDDDLLL",
    "UUUFFFRRRUUU",
    "RRRDDDBBBUUU",
    "LLLDDDBBBUUU",
    "DDDRRRBBBLLL",
]
